apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-hello
  labels:
    app: nodejs-hello
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nodejs-hello
  template:
    metadata:
      labels:
        app: nodejs-hello
        tier: nodejs-hello
    spec:
      containers:
      - name: nodejs-hello
        image: gtaroadrash/hello:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: nodejs-hello

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-hello
  labels:
    app: nodejs-hello
spec:
  selector:
    app: nodejs-hello
    tier: nodejs-hello
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer
